title: ""
email: simon.pedro.g@gmail.com
description: >- 
  Fulbright Scholar and AI Master's student at the University of Utah.
baseurl: ""
url: "https://simonpedrog.github.io"
theme: jekyll-theme-minimal
